on:
  push:
    branches:
      -master





jobs:
  build:
    runs-on: ubunttu-latest


    steps:
      - name: 'Testing Github action'
        run: pwd


      - name: 'Testing Printing'
        run: echo Radwa